project:
  type: website
  output-dir: docs

website:
  title: "AK HCD Short Reports"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Beaver_coho_analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

